apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - name: http
      protocol: TCP
      port: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web
spec:
  gateways:
  - ingressgateway
  hosts:
  - "web.rnakamine.com"
  http:
  - redirect:
      authority: rnakamine.net
